name = "WellKnownGeometry"
uuid = "0f680547-7be7-4555-8820-bb198eeb646b"
authors = ["Maarten Pronk <git@evetion.nl>", "Julia Computing and contributors."]
version = "0.1.0"

[deps]
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[compat]
GeoFormatTypes = "0.4"
GeoInterface = "1.0"
julia = "1.6"
